name: Go Test

on:
  push:
  pull_request:

jobs:
  test:
    if: >-
      (github.event_name == 'push' && github.ref_name == github.event.repository.default_branch) ||
      (github.event_name == 'pull_request' && github.base_ref == github.event.repository.default_branch)

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Run tests
        run: go test -v ./...